#!/bin/bash
# Wrapper for launching kubelet via rkt-fly stage1.
#
# Make sure to set KUBELET_VERSION to an image tag published here:
# https://quay.io/repository/coreos/hyperkube?tab=tags Alternatively,
# override $KUBELET_ACI to a custom location.

set -e

if [ -z "${KUBELET_VERSION}" ]; then
    echo "ERROR: must set KUBELET_VERSION"
    exit 1
fi

KUBELET_ACI="${KUBELET_ACI:-gcr.io/google_containers/hyperkube}"

mkdir --parents /etc/kubernetes
mkdir --parents /var/lib/docker
mkdir --parents /var/lib/kubelet
mkdir --parents /run/kubelet
mkdir --parents /etc/cni/net.d
mkdir --parents /opt/cni/bin
mkdir --parents /var/lib/etcd

exec /usr/bin/docker run \
  --rm \
  -v /:/rootfs:ro \
  -v /sys:/sys:rw \
  -v /etc/kubernetes:/etc/kubernetes:rw \
  -v /var/lib/docker:/var/lib/docker:rw \
  -v /var/lib/kubelet:/var/lib/kubelet:rw \
  -v /etc/cni/net.d:/etc/cni/net.d:rw \
  -v /opt/cni/bin:/opt/cni/bin:rw \
  -v /var/run:/var/run:rw \
  -v /sbin/modprobe:/sbin/modprobe:ro \
  -v /lib/modules:/lib/modules:ro \
  --privileged=true \
  --net=host \
  --pid=host \
  --security-opt seccomp=unconfined \
  ${KUBELET_ACI}:${KUBELET_VERSION} /kubelet --containerized "$@"
  
  # sample of kubelet args
  # --network-plugin=cni --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
